language: ruby
rvm: 2.1.1
services: postgresql
bundler_args: --without development production --deployment
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database bonsai_heart_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - bundle exec rake spec
  - bundle exec teaspoon
deploy:
  provider: heroku
  api_key:
    secure: Bem/owvClQLmT3ly6mSKZkh0y9UEVxgAJKuIrL0UW8D6BjZeOk3YYFKGYBhKYE87qORbUWb+7ijDXm9oNhGtVEyttVJ3i5LDMq9tiNLs5uRidL5M6bfuqQAFbgEhAKx9VRzqHTMhMf1/hcZy9eO5ZFI/rU18jGIQI7NyxciB1yE=
  app: bonsai-heart
  run:
    - "rake db:migrate"
    - restart
notifications:
  email: false
