language: ruby
rvm: 2.0.0
services: postgresql
bundler_args: --without development production --deployment
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database bonsai_heart_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: Bem/owvClQLmT3ly6mSKZkh0y9UEVxgAJKuIrL0UW8D6BjZeOk3YYFKGYBhKYE87qORbUWb+7ijDXm9oNhGtVEyttVJ3i5LDMq9tiNLs5uRidL5M6bfuqQAFbgEhAKx9VRzqHTMhMf1/hcZy9eO5ZFI/rU18jGIQI7NyxciB1yE=
  app: bonsai_heart
  on:
    repo: StefanoGermani/bonsai_heart
