development:
  adapter: postgresql
  encoding: unicode
  database: bonsai_heart_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: bonsai_heart_test
  pool: 5
  username: postgres
  password: postgres

