development:
  adapter: postgresql
  encoding: UTF-8
  database: bonsai_heart_development
  pool: 5
  template: template0
  collation: en_US.UTF8
  ctype: en_US.UTF8
  username: bonsaiheart
  password: password

test:
  adapter: postgresql
  encoding: UTF-8
  database: bonsai_heart_test
  pool: 5
  template: template0
  collation: en_US.UTF8
  ctype: en_US.UTF8
  username: bonsaiheart
  password: password

